# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
    - master
    - hotfix/*
    - release/*
    - restapi*
  paths:
    include:
    - sdk/securityinsights/

pr:
  branches:
    include:
    - master
    - feature/*
    - hotfix/*
    - release/*
    - restapi*
  paths:
    include:
    - sdk/securityinsights/

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: securityinsights
    Artifacts:
    - name: azure_mgmt_securityinsights
      safeName: azuremgmtsecurityinsights
